/* =====================================================================
   GoodMonk Performance Command Center — Dashboard logic
   ---------------------------------------------------------------------
   Static site, no backend: reads JSON files generated by
   dashboard_data.py, renders everything client-side, and polls those
   same JSON files every 30s so the page updates without a reload.
   ===================================================================== */

const DATA_BASE = "data";
const REFRESH_MS = 30_000;

// Priority pages (mirrors config.PAGES_PRIORITY) shown first in the page
// selector dropdown — these are the 6 commercial pages from the July 2026
// manager review.
const PRIORITY_PAGE_ORDER = ["Homepage", "Shop All", "H50+", "FNM", "Plant Protein Roti", "Fiber Fix"];

// Benchmark reference lines for the trend charts (fix #2). Keep these in
// sync with config.py's BENCHMARK_* constants — this is a static JS file
// with no server templating, so the values are duplicated here on purpose.
const BENCHMARKS = {
  score: [
    { value: 60, label: "Our Target", colorVar: "--accent-teal" },
    { value: 90, label: "Google Good", colorVar: "--accent-blue" },
  ],
  lcp: [
    { value: 2.5, label: "Good", colorVar: "--accent-teal" },
    { value: 4, label: "Poor", colorVar: "--accent-red" },
  ],
  speedIndex: [
    { value: 3.4, label: "Good", colorVar: "--accent-teal" },
    { value: 5.8, label: "Poor", colorVar: "--accent-red" },
  ],
};

// Traffic-light color lookup shared by KPIs, page cards, and metric chips.
const TIER_COLOR = { green: "var(--accent-teal)", yellow: "var(--accent-amber)", red: "var(--accent-red)", grey: "var(--text-faint)" };

const state = {
  summary: null,
  pages: [],
  trends: { daily: { overall: [], pages: {} }, weekly: { overall: [], pages: {} }, monthly: { overall: [], pages: {} } },
  history: [],
  granularity: "daily",
  selectedPage: "__overall__",
  charts: {},
};

// --- Data loading ---------------------------------------------------------

async function fetchJSON(path) {
  const res = await fetch(`${DATA_BASE}/${path}?t=${Date.now()}`, { cache: "no-store" });
  if (!res.ok) throw new Error(`Failed to load ${path}: ${res.status}`);
  return res.json();
}

async function loadAll() {
  try {
    const [summary, pages, trends, history] = await Promise.all([
      fetchJSON("summary.json"),
      fetchJSON("pages.json"),
      fetchJSON("trends.json"),
      fetchJSON("history.json"),
    ]);
    state.summary = summary;
    state.pages = pages;
    state.trends = trends;
    state.history = history;
    renderAll();
  } catch (e) {
    console.error("Dashboard data load failed:", e);
    document.getElementById("load-error").style.display = "block";
  }
}

// --- Timezone: always display IST, regardless of the viewer's own browser
// timezone (a visitor outside India should still see IST, not their local
// time) --------------------------------------------------------------------

function formatIST(isoString) {
  if (!isoString) return "—";
  const date = new Date(isoString);
  if (isNaN(date.getTime())) return "—";
  const formatted = new Intl.DateTimeFormat("en-IN", {
    timeZone: "Asia/Kolkata",
    day: "2-digit", month: "short", year: "numeric",
    hour: "2-digit", minute: "2-digit", hour12: true,
  }).format(date);
  return `${formatted} IST`;
}

// --- Small helpers ----------------------------------------------------------

function escapeHTML(str) {
  if (str === null || str === undefined) return "";
  return String(str)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function resolveCSSVar(varExpr) {
  // Canvas (used by Chart.js annotations) can't resolve var(--x) itself —
  // this pulls the actual computed color so benchmark lines render.
  const match = /var\((--[a-zA-Z0-9-]+)\)/.exec(varExpr);
  const name = match ? match[1] : varExpr;
  return getComputedStyle(document.documentElement).getPropertyValue(name).trim() || varExpr;
}

// --- Rendering: vitals bar -------------------------------------------------

function overallStatusColor() {
  const s = state.summary;
  if (!s) return "grey";
  if (s.critical_count > 0) return "red";
  if (s.warning_count > 0) return "yellow";
  if (s.healthy_count > 0) return "green";
  return "grey";
}

function renderVitalsBar() {
  const s = state.summary || {};
  const color = overallStatusColor();

  document.getElementById("status-dot").className = `status-dot status-color-${color}`;
  document.getElementById("last-run").textContent = formatIST(s.generated_at);
  document.getElementById("next-run").textContent = formatIST(s.next_scheduled_run);
  document.getElementById("run-status").textContent = (s.last_run_status || "never_run").replace(/_/g, " ");

  const running = document.getElementById("running-count");
  running.textContent = state.pages.filter(p => p.status_color !== "grey").length + " / " + (s.total_urls ?? state.pages.length);

  updatePulse(color);
}

// --- Signature element: animated heartbeat/pulse line ----------------------

let pulsePhase = 0;
function updatePulse(color) {
  const svg = document.getElementById("pulse-svg");
  const path = document.getElementById("pulse-path");
  const colorVar = { green: "var(--accent-teal)", yellow: "var(--accent-amber)", red: "var(--accent-red)", grey: "var(--text-faint)" }[color];
  path.style.color = colorVar;

  // Build a heartbeat-monitor style waveform: flat line with periodic spikes.
  const width = 600, height = 40, mid = height / 2;
  const speed = { green: 1, yellow: 1.4, red: 1.9, grey: 0.4 }[color];
  let d = `M0,${mid}`;
  const segment = 60;
  for (let x = 0; x <= width; x += segment) {
    const beatOffset = (x / segment) % 1;
    d += ` L${x + segment * 0.35},${mid}`;
    d += ` L${x + segment * 0.42},${mid - 14}`;
    d += ` L${x + segment * 0.48},${mid + 10}`;
    d += ` L${x + segment * 0.54},${mid - 4}`;
    d += ` L${x + segment * 0.62},${mid}`;
  }
  path.setAttribute("d", d);
  svg.style.setProperty("--pulse-speed", `${3 / speed}s`);
}

// --- Rendering: KPI strip -------------------------------------------------

function renderKPIs() {
  const s = state.summary || {};
  const kpis = [
    { label: "Total URLs", value: s.total_urls ?? "—" },
    { label: "Average Score", value: s.average_score ?? "—" },
    { label: "Best Page", value: s.best_page ?? "—", sub: true },
    { label: "Worst Page", value: s.worst_page ?? "—", sub: true },
    { label: "Healthy", value: s.healthy_count ?? 0, color: "var(--accent-teal)" },
    { label: "Warning", value: s.warning_count ?? 0, color: "var(--accent-amber)" },
    { label: "Critical", value: s.critical_count ?? 0, color: "var(--accent-red)" },
    { label: "No Data Yet", value: s.no_data_count ?? 0, color: "var(--text-faint)" },
  ];
  const el = document.getElementById("kpi-strip");
  el.innerHTML = kpis.map(k => `
    <div class="kpi-card">
      <div class="kpi-label">${k.label}</div>
      <div class="kpi-value" style="${k.color ? `color:${k.color}` : ""}; ${k.sub ? "font-size:16px;" : ""}">${escapeHTML(k.value)}</div>
    </div>
  `).join("");
}

// --- Rendering: page vitals grid (fix #5 — expanded cards) -----------------

function trendArrowHTML(delta) {
  if (delta === null || delta === undefined) return `<span class="pc-trend pc-trend-flat">—</span>`;
  if (delta > 0) return `<span class="pc-trend pc-trend-up">↑ +${delta}</span>`;
  if (delta < 0) return `<span class="pc-trend pc-trend-down">↓ ${delta}</span>`;
  return `<span class="pc-trend pc-trend-flat">→ 0</span>`;
}

function metricChip(label, value, unit, tier) {
  const color = TIER_COLOR[tier] || TIER_COLOR.grey;
  const display = (value === null || value === undefined) ? "—" : `${value}${unit}`;
  return `<span style="color:${color}">${label} ${display}</span>`;
}

function renderPagesGrid() {
  const el = document.getElementById("pages-grid");
  if (!state.pages.length) {
    el.innerHTML = `<div class="empty-state">No runs yet. The first scheduled run will populate this grid.</div>`;
    return;
  }
  el.innerHTML = state.pages.map(p => {
    const latest = p.latest || {};
    const tiers = p.metric_tiers || {};
    const overallColor = TIER_COLOR[p.status_color] || TIER_COLOR.grey;

    const tbt = latest["TBT"];
    const tbtMs = (tbt === null || tbt === undefined || tbt === "") ? null : Math.round(tbt * 1000);

    const opportunities = Array.isArray(p.top_opportunities) ? p.top_opportunities : [];
    const topOpportunities = opportunities.slice(0, 3);
    const topIssue = opportunities[0];

    return `
    <div class="page-card" style="color:${overallColor}">
      <div class="pc-head">
        <div class="pc-name" style="color:var(--text)">${escapeHTML(p.name)}</div>
        <div class="pc-score-wrap">
          <div class="pc-score" style="color:${overallColor}">${latest["Performance Score"] ?? "—"}</div>
          ${trendArrowHTML(p.score_trend)}
        </div>
      </div>
      <div class="pc-metrics-grid">
        ${metricChip("LCP", latest["LCP"] ?? null, "s", tiers.lcp)}
        ${metricChip("CLS", latest["CLS"] ?? null, "", tiers.cls)}
        ${metricChip("TTFB", latest["TTFB"] ?? null, "s", tiers.ttfb)}
        ${metricChip("TBT", tbtMs, "ms", tiers.tbt)}
      </div>
      ${topIssue ? `<div class="pc-top-issue">Top issue: ${escapeHTML(topIssue.title)}${topIssue.display_value ? ` (${escapeHTML(topIssue.display_value)})` : ""}</div>` : ""}
      ${topOpportunities.length ? `
      <div class="pc-opportunities">
        <div class="pc-opp-title">Why is this page slow?</div>
        <ul>
          ${topOpportunities.map(o => `<li>${escapeHTML(o.title)}${o.display_value ? ` — ${escapeHTML(o.display_value)}` : ""}</li>`).join("")}
        </ul>
      </div>` : ""}
      <div class="pc-footer">
        <span>${p.total_runs} runs · ${p.failed_runs} failed</span>
        ${latest["Report URL"] ? `<a href="${latest["Report URL"]}" target="_blank" rel="noopener">Report ↗</a>` : ""}
      </div>
    </div>`;
  }).join("");
}

// --- Rendering: page selector (fix #3) --------------------------------------

function populatePageSelector() {
  const sel = document.getElementById("page-selector");
  const previous = state.selectedPage;

  const names = state.pages.map(p => p.name);
  const priority = PRIORITY_PAGE_ORDER.filter(n => names.includes(n));
  const rest = names.filter(n => !PRIORITY_PAGE_ORDER.includes(n));
  const ordered = [...priority, ...rest];

  const options = [`<option value="__overall__">All Pages (overall)</option>`]
    .concat(ordered.map(n => `<option value="${escapeHTML(n)}">${escapeHTML(n)}</option>`));
  sel.innerHTML = options.join("");

  // Keep the previous selection if that page still exists, else fall back.
  sel.value = (previous === "__overall__" || ordered.includes(previous)) ? previous : "__overall__";
  state.selectedPage = sel.value;
}

// --- Rendering: trend charts (Chart.js + annotation plugin) ----------------

function chartTheme() {
  const styles = getComputedStyle(document.documentElement);
  return {
    text: styles.getPropertyValue("--text-muted").trim(),
    grid: styles.getPropertyValue("--hairline").trim(),
    teal: styles.getPropertyValue("--accent-teal").trim(),
    amber: styles.getPropertyValue("--accent-amber").trim(),
    blue: styles.getPropertyValue("--accent-blue").trim(),
  };
}

function benchmarkAnnotations(key) {
  const lines = BENCHMARKS[key] || [];
  const annotations = {};
  lines.forEach((line, i) => {
    const color = resolveCSSVar(`var(${line.colorVar})`);
    annotations[`${key}_benchmark_${i}`] = {
      type: "line",
      yMin: line.value,
      yMax: line.value,
      borderColor: color,
      borderWidth: 1.5,
      borderDash: [6, 4],
      label: {
        display: true,
        content: `${line.label} (${line.value})`,
        position: "end",
        backgroundColor: "transparent",
        color: color,
        font: { size: 10, family: "JetBrains Mono" },
        yAdjust: -8,
      },
    };
  });
  return annotations;
}

function buildLineChart(canvasId, labels, datasets, benchmarkKey) {
  const ctx = document.getElementById(canvasId).getContext("2d");
  if (state.charts[canvasId]) state.charts[canvasId].destroy();
  const theme = chartTheme();

  // Defensive: the annotation plugin should self-register from its CDN
  // script tag, but register it explicitly if that hasn't happened yet
  // (e.g. script load ordering) so benchmark lines never silently vanish.
  if (window.Chart && window["chartjs-plugin-annotation"] && !Chart.registry.plugins.get("annotation")) {
    Chart.register(window["chartjs-plugin-annotation"]);
  }

  state.charts[canvasId] = new Chart(ctx, {
    type: "line",
    data: { labels, datasets },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      interaction: { mode: "index", intersect: false },
      plugins: {
        legend: { labels: { color: theme.text, font: { family: "Inter", size: 11 } } },
        annotation: { annotations: benchmarkKey ? benchmarkAnnotations(benchmarkKey) : {} },
      },
      scales: {
        x: { ticks: { color: theme.text, font: { size: 10 } }, grid: { color: theme.grid } },
        y: { ticks: { color: theme.text, font: { size: 10 } }, grid: { color: theme.grid } },
      },
      elements: { point: { radius: 2 }, line: { tension: 0.3 } },
    },
  });
}

function getActiveSeries() {
  const granularityData = state.trends[state.granularity];

  if (!granularityData) return { series: [], stale: false };

  if (Array.isArray(granularityData)) {
    // Old pre-per-page trends.json shape (from before the per-page trends
    // fix was deployed) is still what's committed. It only has one
    // overall-average series — there is no real per-page data in it yet.
    // Silently falling back to that same overall array for every page
    // selection is exactly what caused "every page shows identical data"
    // — so instead of doing that, return nothing for a specific page and
    // let renderTrendCharts show an explicit notice. "All Pages" can
    // still be served from this shape.
    if (state.selectedPage === "__overall__") return { series: granularityData, stale: false };
    return { series: [], stale: true };
  }

  if (state.selectedPage === "__overall__") return { series: granularityData.overall || [], stale: false };
  return { series: (granularityData.pages && granularityData.pages[state.selectedPage]) || [], stale: false };
}

function renderTrendCharts() {
  const theme = chartTheme();
  const { series, stale } = getActiveSeries();
  const labels = series.map(s => s.period);

  const notice = document.getElementById("trend-stale-notice");
  if (stale) {
    notice.textContent = `Per-page trend history for "${state.selectedPage}" isn't in the current data yet — it appears after the next scheduled run regenerates trends.json. Showing "All Pages" until then.`;
    notice.style.display = "block";
  } else {
    notice.style.display = "none";
  }

  buildLineChart("chart-score", labels, [{
    label: "Avg Score", data: series.map(s => s.avg_score),
    borderColor: theme.teal, backgroundColor: theme.teal + "33", fill: true,
  }], "score");
  buildLineChart("chart-lcp", labels, [{
    label: "Avg LCP (s)", data: series.map(s => s.avg_lcp),
    borderColor: theme.amber, backgroundColor: theme.amber + "33", fill: true,
  }], "lcp");
  buildLineChart("chart-load", labels, [{
    label: "Avg Speed Index (s)", data: series.map(s => s.avg_fully_loaded),
    borderColor: theme.blue, backgroundColor: theme.blue + "33", fill: true,
  }], "speedIndex");

  document.querySelectorAll(".granularity-toggle button").forEach(btn => {
    btn.classList.toggle("active", btn.dataset.granularity === state.granularity);
  });
}

// --- Rendering: history table with search/filter ----------------------------

function getFilteredHistory() {
  const q = document.getElementById("search-input").value.trim().toLowerCase();
  const statusFilter = document.getElementById("status-filter").value;
  return state.history.filter(r => {
    if (statusFilter !== "all" && r.Status !== statusFilter) return false;
    if (!q) return true;
    return (r._page_name || "").toLowerCase().includes(q) || (r._sheet_name || "").toLowerCase().includes(q);
  });
}

function renderHistoryTable() {
  const rows = getFilteredHistory().slice().reverse().slice(0, 500); // most recent first, capped for render speed
  const tbody = document.getElementById("history-tbody");

  if (!rows.length) {
    tbody.innerHTML = `<tr><td colspan="8" class="empty-state">No matching history rows.</td></tr>`;
    return;
  }

  tbody.innerHTML = rows.map(r => {
    const isOk = r.Status === "OK";
    const badgeColor = isOk ? "var(--accent-teal)" : "var(--accent-red)";
    return `
    <tr>
      <td>${escapeHTML(r.Date || "")} ${escapeHTML(r.Time || "")} IST</td>
      <td>${escapeHTML(r._page_name || r._sheet_name || "")}</td>
      <td>${r["Performance Score"] ?? "—"}</td>
      <td>${escapeHTML(r["Grade"] ?? "—")}</td>
      <td>${r["LCP"] ?? "—"}</td>
      <td>${r["Fully Loaded"] ?? "—"}</td>
      <td><span class="badge" style="background:${badgeColor}22;color:${badgeColor}">${escapeHTML(r.Status || "—")}</span></td>
      <td>${r["Report URL"] ? `<a href="${r["Report URL"]}" target="_blank" rel="noopener">View</a>` : "—"}</td>
    </tr>`;
  }).join("");
}

// --- Export ------------------------------------------------------------------

function toCSV(rows) {
  if (!rows.length) return "";
  const headers = ["Date", "Time", "_page_name", "Performance Score", "Grade", "LCP", "Onload", "Fully Loaded", "TTFB", "CLS", "TBT", "Report URL", "Status"];
  const lines = [headers.join(",")];
  rows.forEach(r => {
    lines.push(headers.map(h => `"${String(r[h] ?? "").replace(/"/g, '""')}"`).join(","));
  });
  return lines.join("\n");
}

function downloadBlob(content, filename, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function exportCSV() {
  const rows = getFilteredHistory();
  downloadBlob(toCSV(rows), `goodmonk-performance-${new Date().toISOString().slice(0, 10)}.csv`, "text/csv");
}

function exportExcel() {
  // Excel opens well-formed CSV directly; avoids pulling in a full XLSX
  // library for a static dashboard. Renamed .xls with an HTML table is
  // the classic zero-dependency trick for real Excel formatting.
  const rows = getFilteredHistory();
  const headers = ["Date", "Time", "Page", "Score", "Grade", "LCP", "Fully Loaded", "Status", "Report URL"];
  let html = `<table><tr>${headers.map(h => `<th>${h}</th>`).join("")}</tr>`;
  rows.forEach(r => {
    html += `<tr><td>${r.Date || ""}</td><td>${r.Time || ""}</td><td>${r._page_name || ""}</td>` +
      `<td>${r["Performance Score"] ?? ""}</td><td>${r["Grade"] ?? ""}</td><td>${r["LCP"] ?? ""}</td>` +
      `<td>${r["Fully Loaded"] ?? ""}</td><td>${r["Status"] ?? ""}</td><td>${r["Report URL"] ?? ""}</td></tr>`;
  });
  html += "</table>";
  downloadBlob(html, `goodmonk-performance-${new Date().toISOString().slice(0, 10)}.xls`, "application/vnd.ms-excel");
}

// --- Dark mode -----------------------------------------------------------

function initTheme() {
  const saved = localStorage.getItem("gm-theme") || "dark";
  document.documentElement.setAttribute("data-theme", saved);
  document.getElementById("theme-toggle").textContent = saved === "dark" ? "☀" : "☾";
}

function toggleTheme() {
  const current = document.documentElement.getAttribute("data-theme") || "dark";
  const next = current === "dark" ? "light" : "dark";
  document.documentElement.setAttribute("data-theme", next);
  localStorage.setItem("gm-theme", next);
  document.getElementById("theme-toggle").textContent = next === "dark" ? "☀" : "☾";
  renderTrendCharts(); // re-theme chart colors
}

// --- Wire-up ---------------------------------------------------------------

function renderAll() {
  renderVitalsBar();
  renderKPIs();
  renderPagesGrid();
  populatePageSelector();
  renderTrendCharts();
  renderHistoryTable();
  document.getElementById("load-error").style.display = "none";
}

function initControls() {
  document.getElementById("theme-toggle").addEventListener("click", toggleTheme);
  document.getElementById("search-input").addEventListener("input", renderHistoryTable);
  document.getElementById("status-filter").addEventListener("change", renderHistoryTable);
  document.getElementById("export-csv").addEventListener("click", exportCSV);
  document.getElementById("export-excel").addEventListener("click", exportExcel);
  document.getElementById("refresh-now").addEventListener("click", loadAll);
  document.getElementById("page-selector").addEventListener("change", (e) => {
    state.selectedPage = e.target.value;
    renderTrendCharts();
  });

  document.querySelectorAll(".granularity-toggle button").forEach(btn => {
    btn.addEventListener("click", () => {
      state.granularity = btn.dataset.granularity;
      renderTrendCharts();
    });
  });
}

document.addEventListener("DOMContentLoaded", () => {
  initTheme();
  initControls();
  loadAll();
  setInterval(loadAll, REFRESH_MS);
});
