/* =====================================================================
   GoodMonk Performance Command Center — Dashboard logic
   ---------------------------------------------------------------------
   Static site, no backend: reads JSON files generated by
   dashboard_data.py, renders everything client-side, and polls those
   same JSON files every 30s so the page updates without a reload.
   ===================================================================== */

const DATA_BASE = "data";
const REFRESH_MS = 30_000;

const state = {
  summary: null,
  pages: [],
  trends: { daily: [], weekly: [], monthly: [] },
  history: [],
  granularity: "daily",
  charts: {},
};

// --- Data loading ---------------------------------------------------------

async function fetchJSON(path) {
  const res = await fetch(`${DATA_BASE}/${path}?t=${Date.now()}`, { cache: "no-store" });
  if (!res.ok) throw new Error(`Failed to load ${path}: ${res.status}`);
  return res.json();
}

async function loadAll() {
  try {
    const [summary, pages, trends, history] = await Promise.all([
      fetchJSON("summary.json"),
      fetchJSON("pages.json"),
      fetchJSON("trends.json"),
      fetchJSON("history.json"),
    ]);
    state.summary = summary;
    state.pages = pages;
    state.trends = trends;
    state.history = history;
    renderAll();
  } catch (e) {
    console.error("Dashboard data load failed:", e);
    document.getElementById("load-error").style.display = "block";
  }
}

// --- Rendering: vitals bar -------------------------------------------------

function overallStatusColor() {
  const s = state.summary;
  if (!s) return "grey";
  if (s.critical_count > 0) return "red";
  if (s.warning_count > 0) return "yellow";
  if (s.healthy_count > 0) return "green";
  return "grey";
}

function renderVitalsBar() {
  const s = state.summary || {};
  const color = overallStatusColor();

  document.getElementById("status-dot").className = `status-dot status-color-${color}`;
  document.getElementById("last-run").textContent = s.generated_at ? new Date(s.generated_at).toLocaleString() : "—";
  document.getElementById("next-run").textContent = s.next_scheduled_run ? new Date(s.next_scheduled_run).toLocaleString() : "—";
  document.getElementById("run-status").textContent = (s.last_run_status || "never_run").replace(/_/g, " ");

  const running = document.getElementById("running-count");
  running.textContent = state.pages.filter(p => p.status_color !== "grey").length + " / " + (s.total_urls ?? state.pages.length);

  updatePulse(color);
}

// --- Signature element: animated heartbeat/pulse line ----------------------

let pulsePhase = 0;
function updatePulse(color) {
  const svg = document.getElementById("pulse-svg");
  const path = document.getElementById("pulse-path");
  const colorVar = { green: "var(--accent-teal)", yellow: "var(--accent-amber)", red: "var(--accent-red)", grey: "var(--text-faint)" }[color];
  path.style.color = colorVar;

  // Build a heartbeat-monitor style waveform: flat line with periodic spikes.
  const width = 600, height = 40, mid = height / 2;
  const speed = { green: 1, yellow: 1.4, red: 1.9, grey: 0.4 }[color];
  let d = `M0,${mid}`;
  const segment = 60;
  for (let x = 0; x <= width; x += segment) {
    const beatOffset = (x / segment) % 1;
    d += ` L${x + segment * 0.35},${mid}`;
    d += ` L${x + segment * 0.42},${mid - 14}`;
    d += ` L${x + segment * 0.48},${mid + 10}`;
    d += ` L${x + segment * 0.54},${mid - 4}`;
    d += ` L${x + segment * 0.62},${mid}`;
  }
  path.setAttribute("d", d);
  svg.style.setProperty("--pulse-speed", `${3 / speed}s`);
}

// --- Rendering: KPI strip -------------------------------------------------

function renderKPIs() {
  const s = state.summary || {};
  const kpis = [
    { label: "Total URLs", value: s.total_urls ?? "—" },
    { label: "Average Score", value: s.average_score ?? "—" },
    { label: "Best Page", value: s.best_page ?? "—", sub: true },
    { label: "Worst Page", value: s.worst_page ?? "—", sub: true },
    { label: "Healthy", value: s.healthy_count ?? 0, color: "var(--accent-teal)" },
    { label: "Warning", value: s.warning_count ?? 0, color: "var(--accent-amber)" },
    { label: "Critical", value: s.critical_count ?? 0, color: "var(--accent-red)" },
    { label: "No Data Yet", value: s.no_data_count ?? 0, color: "var(--text-faint)" },
  ];
  const el = document.getElementById("kpi-strip");
  el.innerHTML = kpis.map(k => `
    <div class="kpi-card">
      <div class="kpi-label">${k.label}</div>
      <div class="kpi-value" style="${k.color ? `color:${k.color}` : ""}; ${k.sub ? "font-size:16px;" : ""}">${k.value}</div>
    </div>
  `).join("");
}

// --- Rendering: page vitals grid -------------------------------------------

function renderPagesGrid() {
  const el = document.getElementById("pages-grid");
  if (!state.pages.length) {
    el.innerHTML = `<div class="empty-state">No runs yet. The first scheduled run will populate this grid.</div>`;
    return;
  }
  el.innerHTML = state.pages.map(p => {
    const latest = p.latest || {};
    const color = { green: "var(--accent-teal)", yellow: "var(--accent-amber)", red: "var(--accent-red)", grey: "var(--text-faint)" }[p.status_color];
    return `
    <div class="page-card" style="color:${color}">
      <div class="pc-head">
        <div class="pc-name" style="color:var(--text)">${p.name}</div>
        <div class="pc-score" style="color:${color}">${latest["Performance Score"] ?? "—"}</div>
      </div>
      <div class="pc-metrics">
        <span>LCP ${latest["LCP"] ?? "—"}s</span>
        <span>Grade ${latest["Grade"] ?? "—"}</span>
      </div>
      <div class="pc-footer">
        <span>${p.total_runs} runs · ${p.failed_runs} failed</span>
        ${latest["Report URL"] ? `<a href="${latest["Report URL"]}" target="_blank" rel="noopener">Report ↗</a>` : ""}
      </div>
    </div>`;
  }).join("");
}

// --- Rendering: trend charts (Chart.js) ------------------------------------

function chartTheme() {
  const styles = getComputedStyle(document.documentElement);
  return {
    text: styles.getPropertyValue("--text-muted").trim(),
    grid: styles.getPropertyValue("--hairline").trim(),
    teal: styles.getPropertyValue("--accent-teal").trim(),
    amber: styles.getPropertyValue("--accent-amber").trim(),
    blue: styles.getPropertyValue("--accent-blue").trim(),
  };
}

function buildLineChart(canvasId, labels, datasets) {
  const ctx = document.getElementById(canvasId).getContext("2d");
  if (state.charts[canvasId]) state.charts[canvasId].destroy();
  const theme = chartTheme();
  state.charts[canvasId] = new Chart(ctx, {
    type: "line",
    data: { labels, datasets },
    options: {
      responsive: true,
      maintainAspectRatio: false,
      interaction: { mode: "index", intersect: false },
      plugins: { legend: { labels: { color: theme.text, font: { family: "Inter", size: 11 } } } },
      scales: {
        x: { ticks: { color: theme.text, font: { size: 10 } }, grid: { color: theme.grid } },
        y: { ticks: { color: theme.text, font: { size: 10 } }, grid: { color: theme.grid } },
      },
      elements: { point: { radius: 2 }, line: { tension: 0.3 } },
    },
  });
}

function renderTrendCharts() {
  const theme = chartTheme();
  const series = state.trends[state.granularity] || [];
  const labels = series.map(s => s.period);

  buildLineChart("chart-score", labels, [{
    label: "Avg Score", data: series.map(s => s.avg_score),
    borderColor: theme.teal, backgroundColor: theme.teal + "33", fill: true,
  }]);
  buildLineChart("chart-lcp", labels, [{
    label: "Avg LCP (s)", data: series.map(s => s.avg_lcp),
    borderColor: theme.amber, backgroundColor: theme.amber + "33", fill: true,
  }]);
  buildLineChart("chart-load", labels, [{
    label: "Avg Fully Loaded (s)", data: series.map(s => s.avg_fully_loaded),
    borderColor: theme.blue, backgroundColor: theme.blue + "33", fill: true,
  }]);

  document.querySelectorAll(".granularity-toggle button").forEach(btn => {
    btn.classList.toggle("active", btn.dataset.granularity === state.granularity);
  });
}

// --- Rendering: history table with search/filter ----------------------------

function getFilteredHistory() {
  const q = document.getElementById("search-input").value.trim().toLowerCase();
  const statusFilter = document.getElementById("status-filter").value;
  return state.history.filter(r => {
    if (statusFilter !== "all" && r.Status !== statusFilter) return false;
    if (!q) return true;
    return (r._page_name || "").toLowerCase().includes(q) || (r._sheet_name || "").toLowerCase().includes(q);
  });
}

function renderHistoryTable() {
  const rows = getFilteredHistory().slice().reverse().slice(0, 500); // most recent first, capped for render speed
  const tbody = document.getElementById("history-tbody");

  if (!rows.length) {
    tbody.innerHTML = `<tr><td colspan="8" class="empty-state">No matching history rows.</td></tr>`;
    return;
  }

  tbody.innerHTML = rows.map(r => {
    const isOk = r.Status === "OK";
    const badgeColor = isOk ? "var(--accent-teal)" : "var(--accent-red)";
    return `
    <tr>
      <td>${r.Date || ""} ${r.Time || ""}</td>
      <td>${r._page_name || r._sheet_name || ""}</td>
      <td>${r["Performance Score"] ?? "—"}</td>
      <td>${r["Grade"] ?? "—"}</td>
      <td>${r["LCP"] ?? "—"}</td>
      <td>${r["Fully Loaded"] ?? "—"}</td>
      <td><span class="badge" style="background:${badgeColor}22;color:${badgeColor}">${r.Status || "—"}</span></td>
      <td>${r["Report URL"] ? `<a href="${r["Report URL"]}" target="_blank" rel="noopener">View</a>` : "—"}</td>
    </tr>`;
  }).join("");
}

// --- Export ------------------------------------------------------------------

function toCSV(rows) {
  if (!rows.length) return "";
  const headers = ["Date", "Time", "_page_name", "Performance Score", "Grade", "LCP", "Onload", "Fully Loaded", "TTFB", "CLS", "TBT", "Report URL", "Status"];
  const lines = [headers.join(",")];
  rows.forEach(r => {
    lines.push(headers.map(h => `"${String(r[h] ?? "").replace(/"/g, '""')}"`).join(","));
  });
  return lines.join("\n");
}

function downloadBlob(content, filename, mime) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function exportCSV() {
  const rows = getFilteredHistory();
  downloadBlob(toCSV(rows), `goodmonk-performance-${new Date().toISOString().slice(0, 10)}.csv`, "text/csv");
}

function exportExcel() {
  // Excel opens well-formed CSV directly; avoids pulling in a full XLSX
  // library for a static dashboard. Renamed .xls with an HTML table is
  // the classic zero-dependency trick for real Excel formatting.
  const rows = getFilteredHistory();
  const headers = ["Date", "Time", "Page", "Score", "Grade", "LCP", "Fully Loaded", "Status", "Report URL"];
  let html = `<table><tr>${headers.map(h => `<th>${h}</th>`).join("")}</tr>`;
  rows.forEach(r => {
    html += `<tr><td>${r.Date || ""}</td><td>${r.Time || ""}</td><td>${r._page_name || ""}</td>` +
      `<td>${r["Performance Score"] ?? ""}</td><td>${r["Grade"] ?? ""}</td><td>${r["LCP"] ?? ""}</td>` +
      `<td>${r["Fully Loaded"] ?? ""}</td><td>${r["Status"] ?? ""}</td><td>${r["Report URL"] ?? ""}</td></tr>`;
  });
  html += "</table>";
  downloadBlob(html, `goodmonk-performance-${new Date().toISOString().slice(0, 10)}.xls`, "application/vnd.ms-excel");
}

// --- Dark mode -----------------------------------------------------------

function initTheme() {
  const saved = localStorage.getItem("gm-theme") || "dark";
  document.documentElement.setAttribute("data-theme", saved);
  document.getElementById("theme-toggle").textContent = saved === "dark" ? "☀" : "☾";
}

function toggleTheme() {
  const current = document.documentElement.getAttribute("data-theme") || "dark";
  const next = current === "dark" ? "light" : "dark";
  document.documentElement.setAttribute("data-theme", next);
  localStorage.setItem("gm-theme", next);
  document.getElementById("theme-toggle").textContent = next === "dark" ? "☀" : "☾";
  renderTrendCharts(); // re-theme chart colors
}

// --- Wire-up ---------------------------------------------------------------

function renderAll() {
  renderVitalsBar();
  renderKPIs();
  renderPagesGrid();
  renderTrendCharts();
  renderHistoryTable();
  document.getElementById("load-error").style.display = "none";
}

function initControls() {
  document.getElementById("theme-toggle").addEventListener("click", toggleTheme);
  document.getElementById("search-input").addEventListener("input", renderHistoryTable);
  document.getElementById("status-filter").addEventListener("change", renderHistoryTable);
  document.getElementById("export-csv").addEventListener("click", exportCSV);
  document.getElementById("export-excel").addEventListener("click", exportExcel);
  document.getElementById("refresh-now").addEventListener("click", loadAll);

  document.querySelectorAll(".granularity-toggle button").forEach(btn => {
    btn.addEventListener("click", () => {
      state.granularity = btn.dataset.granularity;
      renderTrendCharts();
    });
  });
}

document.addEventListener("DOMContentLoaded", () => {
  initTheme();
  initControls();
  loadAll();
  setInterval(loadAll, REFRESH_MS);
});
