/* =====================================================================
   insights.js — Business Insights tab module
   ---------------------------------------------------------------------
   PLUGIN ARCHITECTURE CONTRACT
   Fetches only dashboard/data/insights.json (numbers + raw Lighthouse
   titles, written by insights_data.py). Translates those raw titles to
   plain English by calling GMBusiness.explainOne() — reusing the SAME
   dictionary the Overview tab uses, so there is exactly one place that
   translation copy lives. Renders only into #tab-insights.

   NOTE ON "AI SUMMARY": the narrative below is generated by simple,
   deterministic rules from real numbers — there is no live AI model
   call in this pipeline. It's labelled "Automated Summary" in the UI
   rather than implying a live generative AI wrote it.
   ===================================================================== */

const GMInsights = (() => {
  const DATA_BASE = "data";
  let initialized = false;
  let trendChart = null;

  async function fetchJSON(path) {
    const res = await fetch(`${DATA_BASE}/${path}?t=${Date.now()}`, { cache: "no-store" });
    if (!res.ok) throw new Error(`${path}: HTTP ${res.status}`);
    return res.json();
  }

  function escapeHTML(str) {
    const div = document.createElement("div");
    div.textContent = str == null ? "" : String(str);
    return div.innerHTML;
  }

  function translateTitle(title) {
    if (!title) return null;
    // See nav.js for why this must be `typeof` and not `window.GMBusiness`.
    if (typeof GMBusiness !== "undefined" && typeof GMBusiness.explainOne === "function") {
      return GMBusiness.explainOne(title);
    }
    return { title, plain: title, impact: "" };
  }

  // --- Score panel ---------------------------------------------------

  function renderScore(data) {
    const ring = document.getElementById("gm-ins-score-ring");
    ring.className = `gm-score-ring ${data.business_score_color || "grey"}`;
    ring.innerHTML = `
      <div class="num">${data.business_score != null ? Math.round(data.business_score) : "—"}</div>
      <div class="lbl">${escapeHTML(data.business_score_label || "No Data")}</div>
    `;

    const labels = { performance: "Performance", journey: "Journey", alerts: "Alerts", availability: "Availability" };
    const breakdown = document.getElementById("gm-ins-breakdown");
    breakdown.innerHTML = Object.entries(labels).map(([key, label]) => {
      const val = (data.components || {})[key];
      const pct = val != null ? Math.round(val) : 0;
      return `<div class="gm-score-bar-row">
        <span class="name">${label}</span>
        <div class="gm-score-bar-track"><div class="gm-score-bar-fill" style="width:${pct}%"></div></div>
        <span class="pct">${val != null ? pct : "—"}</span>
      </div>`;
    }).join("");
  }

  // --- Narrative (rule-based, deterministic) ---------------------------

  function buildNarrative(data) {
    const lines = [];
    lines.push(`Overall website health is <b>${escapeHTML((data.overall_website_health || "unknown").toLowerCase())}</b>.`);

    if (data.pages_slower_than_yesterday > 0) {
      lines.push(`${data.pages_slower_than_yesterday} product page(s) are slower than yesterday.`);
    } else {
      lines.push(`No product pages got slower compared to yesterday.`);
    }

    if (data.checkout_failures_today > 0) {
      lines.push(`<b>${data.checkout_failures_today} confirmed checkout failure(s)</b> detected today.`);
    } else {
      lines.push(`No checkout failures detected today.`);
    }

    if (data.most_common_issue) {
      const t = translateTitle(data.most_common_issue.title);
      lines.push(`Largest issue: ${escapeHTML(t ? t.plain : data.most_common_issue.title)} (affects ${data.most_common_issue.page_count} page(s)).`);
    }

    return lines;
  }

  function recommendedAction(data) {
    if (data.checkout_failures_today > 0) {
      return "Investigate the checkout failure immediately — this directly blocks sales.";
    }
    if (data.most_common_issue) {
      const t = translateTitle(data.most_common_issue.title);
      return t ? `Recommended action: address "${t.title}" — it's the most common issue across your pages.` : "Review the top slow pages below.";
    }
    return "No urgent action needed today — keep monitoring.";
  }

  function renderNarrative(data) {
    document.getElementById("gm-ins-narrative-list").innerHTML =
      buildNarrative(data).map((l) => `<li>${l}</li>`).join("");
    document.getElementById("gm-ins-action").innerHTML = `<b>Recommended Action:</b> ${escapeHTML(recommendedAction(data))}`;
  }

  // --- Top-5 lists -----------------------------------------------------

  function renderSlowPages(data) {
    const el = document.getElementById("gm-ins-slow-pages");
    const rows = data.top_slow_pages || [];
    if (!rows.length) { el.innerHTML = `<div class="gm-empty">No data yet.</div>`; return; }
    el.innerHTML = rows.map((p) => {
      const t = translateTitle(p.top_issue_title);
      return `<div class="gm-insights-list-row">
        <span class="name">${escapeHTML(p.name)}</span>
        <span class="detail">Score ${escapeHTML(p.score)} — ${escapeHTML(t ? t.plain : "")}</span>
      </div>`;
    }).join("");
  }

  function renderFailedJourneys(data) {
    const el = document.getElementById("gm-ins-failed-journeys");
    const rows = data.top_failed_journeys || [];
    if (!rows.length) { el.innerHTML = `<div class="gm-empty">No confirmed checkout failures recorded.</div>`; return; }
    el.innerHTML = rows.map((r) => `
      <div class="gm-insights-list-row">
        <span class="name">${escapeHTML(r.failed_step || "Unknown step")}</span>
        <span class="detail">${escapeHTML(r.finished_at || "")}</span>
      </div>`).join("");
  }

  function renderCommonProblems(data) {
    const el = document.getElementById("gm-ins-common-problems");
    if (!data.most_common_issue) { el.innerHTML = `<div class="gm-empty">No recurring issues detected.</div>`; return; }
    const t = translateTitle(data.most_common_issue.title);
    el.innerHTML = `<div class="gm-insights-list-row">
      <span class="name">${escapeHTML(t ? t.plain : data.most_common_issue.title)}</span>
      <span class="detail">${data.most_common_issue.page_count} page(s) affected</span>
    </div>`;
  }

  // --- Trend chart ---------------------------------------------------

  function renderTrend(data) {
    const canvas = document.getElementById("gm-ins-trend-chart");
    if (!canvas || typeof Chart === "undefined") return;
    const points = data.weekly_trend || [];
    if (trendChart) { trendChart.destroy(); trendChart = null; }
    trendChart = new Chart(canvas.getContext("2d"), {
      type: "line",
      data: {
        labels: points.map((p) => p.date),
        datasets: [{
          label: "Business Health Score",
          data: points.map((p) => p.business_score),
          borderColor: "#2FD9A7",
          backgroundColor: "rgba(47,217,167,0.12)",
          fill: true,
          tension: 0.3,
        }],
      },
      options: {
        responsive: true,
        maintainAspectRatio: false,
        scales: { y: { min: 0, max: 100 } },
        plugins: { legend: { display: false } },
      },
    });
  }

  async function render() {
    let data;
    try {
      data = await fetchJSON("insights.json");
    } catch (err) {
      console.error("[GMInsights] failed to load insights.json:", err);
      document.getElementById("gm-ins-score-ring").innerHTML = `<div class="lbl">No data</div>`;
      return;
    }
    renderScore(data);
    renderNarrative(data);
    renderSlowPages(data);
    renderFailedJourneys(data);
    renderCommonProblems(data);
    renderTrend(data);
  }

  function init() {
    if (initialized) { render(); return; }
    initialized = true;
    render();
  }

  return { init };
})();
